name: "Docker Build and Push"
description: "Log in to GHCR and build/push a multi-platform image"
inputs:
  registry-password:
    description: "The GitHub Token or password for the registry"
    required: true
  docker-push:
    description: "Whether to push the image"
    required: true
    default: "false"
  docker-tags:
    description: "Comma-separated list of tags"
    required: true
  context:
    description: "Docker build context"
    required: false
    default: "."
  cache-scope:
    description: "Scope for the GHA cache"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to GHCR
      if: ${{ inputs.docker-push == 'true' }}
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.registry-password }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v4
      # with:
      #   driver: docker-container

    - name: Build & Push
      uses: docker/build-push-action@v7
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ${{ inputs.context }}
        load: true
        push: ${{ inputs.docker-push }}
        tags: ${{ inputs.docker-tags }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha,scope=${{ inputs.cache-scope }}
        cache-to: type=gha,mode=max,scope=${{ inputs.cache-scope }}
        sbom: true
        provenance: mode=max

    - name: Docker Summary
      shell: bash
      if: ${{ inputs.docker-push == 'true' }}
      run: |
        # Variables for readability
        OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        # REPO_LC=$(echo "${{ inputs.container-name }}" | tr '[:upper:]' '[:lower:]')
        REPO_LC=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
        # get tag with #'s not latest or hash
        TAG="$(echo ${{ inputs.docker-tags }} | tr ',' '\n' | grep -E ':[0-9]+\.[0-9]+\.[0-9]+' | head -n1)"
        APP_NAME=$(basename "${TAG%%:*}")
        DIGEST="${{ steps.build.outputs.digest }}"

        # GHCR Package URL structure
        # PACKAGE_URL="https://github.com/users/$OWNER_LC/packages/container/package/$REPO_LC"
        PACKAGE_URL="https://github.com/${OWNER_LC}/${REPO_LC}/pkgs/container/${REPO_LC}%2F${APP_NAME}"

        {
          echo "## Publish Summary"
          echo "|  |  |"
          echo "| --- | --- |"
          echo "| Container | [${REPO_LC}:${TAG}](${PACKAGE_URL}) |"
          echo ""
          echo "### Pull Command"
          echo '```bash'
          echo "docker pull ghcr.io/${OWNER_LC}/${REPO_LC}/${APP_NAME}:${TAG}"
          echo '```'
          echo "Digest: \`${DIGEST}\`"
        } >> $GITHUB_STEP_SUMMARY
